#include "BluetoothSerial.h"

BluetoothSerial SerialBT;

const int LED_PIN = 2; // Built-in LED on most ESP32 boards
const int PIN_OPEN = 13;
const int PIN_CLOSE = 12;

#define OPEN_NORMAL_STATE  LOW  //set as HIGH/LOW
#define CLOSE_NORMAL_STATE  LOW  //set as HIGH/LOW
#define LED_NORMAL_STATE  LOW  //set as HIGH/LOW

void setup() {
  pinMode(PIN_OPEN, OUTPUT);
  pinMode(PIN_CLOSE, OUTPUT);
  pinMode(LED_PIN, OUTPUT);  //
  Serial.begin(9600);
  digitalWrite(PIN_OPEN, OPEN_NORMAL_STATE);
  digitalWrite(PIN_CLOSE, CLOSE_NORMAL_STATE);

  // Start Classic Bluetooth with a custom device name
  if (!SerialBT.begin("ESP32_LED_Control")) {
    Serial.println("An error occurred initializing Bluetooth");
  } else {
    Serial.println("Bluetooth started. Pair with 'ESP32_LED_Control'.");
  }

  digitalWrite(LED_PIN, !LED_NORMAL_STATE); // Indecator
  delay(100);
  digitalWrite(LED_PIN, LED_NORMAL_STATE); // Indecator
}

void loop() {
  if (SerialBT.available()) {
    char command = SerialBT.read();

    if (command == '1') {
      digitalWrite(PIN_OPEN, !OPEN_NORMAL_STATE); // Turn LED ON
      digitalWrite(LED_PIN, !LED_NORMAL_STATE); // Turn LED ON
      delay(100);
      //Serial.println("LED ON");
      digitalWrite(PIN_OPEN, OPEN_NORMAL_STATE);
      digitalWrite(LED_PIN, LED_NORMAL_STATE); // Turn LED ON
    } else if (command == '0') {
      digitalWrite(PIN_CLOSE, !CLOSE_NORMAL_STATE); // Turn LED ON
      digitalWrite(LED_PIN, !LED_NORMAL_STATE); // Turn LED ON
      delay(100);
      //Serial.println("LED ON");
      digitalWrite(PIN_CLOSE, CLOSE_NORMAL_STATE);
      digitalWrite(LED_PIN, LED_NORMAL_STATE); // Turn LED ON
    }
  }
}